In [53]:
import numpy as np
import pandas as pd

In [9]:
df = pd.read_excel('Task 1 Data set\default_of_credit_card_clients.xls')

In [11]:
df.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE PAY_1  PAY_2  \
0  798fc410-45c1      20000    2          2         1   24     2      2   
1  8a8c8f3b-8eb4     120000    2          2         2   26    -1      2   
2  85698822-43f5      90000    2          2         2   34     0      0   
3  0737c11b-be42      50000    2          2         1   37     0      0   
4  3b7f77cc-dbc0      50000    1          2         1   57    -1      0   

   PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0     -1     -1  ...          0          0          0         0       689   
1      0      0  ...       3272       3455       3261         0      1000   
2      0      0  ...      14331      14948      15549      1518      1500   
3      0      0  ...      28314      28959      29547      2000      2019   
4     -1      0  ...      20940      19146      19131      2000     36681   

   PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0         0         0         0         0                           1  
1      1000      1000         0      2000                           1  
2      1000      1000      1000      5000                           0  
3      1200      1100      1069      1000                           0  
4     10000      9000       689       679                           0  

[5 rows x 25 columns]

In [16]:
np.random.seed(seed=24)
np.random.randint(low=1,high=5,size=100)

array([3, 4, 1, 4, 2, 2, 2, 1, 4, 4, 1, 4, 4, 3, 4, 4, 4, 4, 4, 4, 2, 3,
       4, 4, 2, 4, 2, 4, 1, 1, 3, 1, 4, 2, 2, 1, 4, 3, 2, 2, 3, 3, 2, 3,
       4, 2, 3, 4, 1, 3, 4, 2, 2, 4, 1, 2, 3, 3, 2, 1, 2, 4, 2, 1, 4, 3,
       1, 2, 1, 3, 4, 2, 3, 4, 1, 3, 2, 1, 1, 3, 3, 4, 3, 2, 4, 1, 4, 4,
       4, 4, 1, 4, 3, 2, 4, 4, 3, 3, 2, 4])

In [17]:
is_equal_to_3 = random_integers == 3

In [18]:
is_equal_to_3

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False, False,  True,  True, False,  True, False,
       False,  True, False, False,  True, False, False, False, False,
       False, False,  True,  True, False, False, False, False, False,
       False, False,  True, False, False, False,  True, False, False,
        True, False, False,  True, False, False, False,  True,  True,
       False,  True, False, False, False, False, False, False, False,
       False, False,  True, False, False, False,  True,  True, False,
       False])

In [19]:
is_equal_to_3[:5]

array([ True, False, False, False, False])

In [20]:
sum(is_equal_to_3)

22

In [21]:
random_integers[is_equal_to_3]

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [22]:
df['ID']

0        798fc410-45c1
1        8a8c8f3b-8eb4
2        85698822-43f5
3        0737c11b-be42
4        3b7f77cc-dbc0
             ...      
29995    ecff42d0-bdc6
29996    99d1fa0e-222b
29997    95cdd3e7-4f24
29998    00d03f02-04cd
29999    15d69f9f-5ad3
Name: ID, Length: 30000, dtype: object

In [23]:
df['ID'].value_counts()

3511ed92-c434    2
0d66d575-c461    2
5f38afd8-e138    2
db91a87c-3cbe    2
428b26a3-dca2    2
                ..
d0337e02-f399    1
a418522a-855e    1
8f8940cc-6ea0    1
8ea9c561-d581    1
9d4c11ee-6cb8    1
Name: ID, Length: 29687, dtype: int64

In [25]:
id_check=df['ID'].value_counts()
id_check==2

3511ed92-c434     True
0d66d575-c461     True
5f38afd8-e138     True
db91a87c-3cbe     True
428b26a3-dca2     True
                 ...  
d0337e02-f399    False
a418522a-855e    False
8f8940cc-6ea0    False
8ea9c561-d581    False
9d4c11ee-6cb8    False
Name: ID, Length: 29687, dtype: bool

In [26]:
dupe_mask=id_check==2
dupe_mask[:5]

3511ed92-c434    True
0d66d575-c461    True
5f38afd8-e138    True
db91a87c-3cbe    True
428b26a3-dca2    True
Name: ID, dtype: bool

In [27]:
id_check.index[dupe_mask]

Index(['3511ed92-c434', '0d66d575-c461', '5f38afd8-e138', 'db91a87c-3cbe',
       '428b26a3-dca2', '1d58344c-5793', '999b7824-373c', '01355f46-3f0b',
       '7fe414ae-32f8', '2a8713e6-0f03',
       ...
       'dda76366-a407', 'bbf202ae-a964', '7b7cc3cd-0b76', '129c43ca-42ee',
       'f20d8a3d-d047', '8d3a2576-a958', '3cd5c728-df14', '297edb0f-3bb1',
       '28866128-6286', '3393c9e4-3345'],
      dtype='object', length=313)

In [28]:
dupe_ids = id_counts.index[dupe_mask]
dupe_ids = list(dupe_ids)
len(dupe_ids)

313

In [29]:
df.loc[df['ID'].isin(dupe_ids[0:3]),:].head(10) 

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE PAY_1  PAY_2  \
4565  0d66d575-c461     100000    1          1         1   60     0      0   
4665  0d66d575-c461          0    0          0         0    0     0      0   
5123  3511ed92-c434     180000    2          1         1   47     1     -2   
5223  3511ed92-c434          0    0          0         0    0     0      0   
7070  5f38afd8-e138      80000    1          1         1   40     0      0   
7170  5f38afd8-e138          0    0          0         0    0     0      0   

      PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
4565      0      0  ...     101729      98103      99521      3856      3919   
4665      0      0  ...          0          0          0         0         0   
5123     -1     -1  ...          0          0          0         0      3312   
5223      0      0  ...          0          0          0         0         0   
7070      2      2  ...      30787      34513      34995      3600      1200   
7170      0      0  ...          0          0          0         0         0   

      PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
4565      3986      3865      3760      3863                           1  
4665         0         0         0         0                           0  
5123         0         0         0         0                           1  
5223         0         0         0         0                           0  
7070         0      4246      1200      1500                           1  
7170         0         0         0         0                           0  

[6 rows x 25 columns]

In [30]:
df_zero_mask = df == 0

In [31]:
feature_zero_mask = df_zero_mask.iloc[:,1:].all(axis=1)
sum(feature_zero_mask)

315

In [32]:
df_clean_1 = df.loc[~feature_zero_mask,:].copy()

In [33]:
df_clean_1['ID'].nunique()

29685

In [34]:
df_clean_1

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE PAY_1  PAY_2  \
0      798fc410-45c1      20000    2          2         1   24     2      2   
1      8a8c8f3b-8eb4     120000    2          2         2   26    -1      2   
2      85698822-43f5      90000    2          2         2   34     0      0   
3      0737c11b-be42      50000    2          2         1   37     0      0   
4      3b7f77cc-dbc0      50000    1          2         1   57    -1      0   
...              ...        ...  ...        ...       ...  ...   ...    ...   
29995  ecff42d0-bdc6     220000    1          3         1   39     0      0   
29996  99d1fa0e-222b     150000    1          3         2   43    -1     -1   
29997  95cdd3e7-4f24      30000    1          2         2   37     4      3   
29998  00d03f02-04cd      80000    1          3         1   41     1     -1   
29999  15d69f9f-5ad3      50000    1          2         1   46     0      0   

       PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0         -1     -1  ...          0          0          0         0       689   
1          0      0  ...       3272       3455       3261         0      1000   
2          0      0  ...      14331      14948      15549      1518      1500   
3          0      0  ...      28314      28959      29547      2000      2019   
4         -1      0  ...      20940      19146      19131      2000     36681   
...      ...    ...  ...        ...        ...        ...       ...       ...   
29995      0      0  ...      88004      31237      15980      8500     20000   
29996     -1     -1  ...       8979       5190          0      1837      3526   
29997      2     -1  ...      20878      20582      19357         0         0   
29998      0      0  ...      52774      11855      48944     85900      3409   
29999      0      0  ...      36535      32428      15313      2078      1800   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0             0         0         0         0                           1  
1          1000      1000         0      2000                           1  
2          1000      1000      1000      5000                           0  
3          1200      1100      1069      1000                           0  
4         10000      9000       689       679                           0  
...         ...       ...       ...       ...                         ...  
29995      5003      3047      5000      1000                           0  
29996      8998       129         0         0                           0  
29997     22000      4200      2000      3100                           1  
29998      1178      1926     52964      1804                           1  
29999      1430      1000      1000      1000                           1  

[29685 rows x 25 columns]

In [35]:
df['PAY_1'].unique()

array([2, -1, 0, -2, 1, 'Not available', 3, 4, 8, 7, 5, 6], dtype=object)

In [38]:
df_clean_1[df_clean_1['PAY_1']=='Not available'].count()

ID                            3021
LIMIT_BAL                     3021
SEX                           3021
EDUCATION                     3021
MARRIAGE                      3021
AGE                           3021
PAY_1                         3021
PAY_2                         3021
PAY_3                         3021
PAY_4                         3021
PAY_5                         3021
PAY_6                         3021
BILL_AMT1                     3021
BILL_AMT2                     3021
BILL_AMT3                     3021
BILL_AMT4                     3021
BILL_AMT5                     3021
BILL_AMT6                     3021
PAY_AMT1                      3021
PAY_AMT2                      3021
PAY_AMT3                      3021
PAY_AMT4                      3021
PAY_AMT5                      3021
PAY_AMT6                      3021
default payment next month    3021
dtype: int64

In [39]:
df_clean_2 = df_clean_1.loc[valid_pay_1_mask,:].copy()

In [40]:
df_clean_2.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE PAY_1  PAY_2  \
0  798fc410-45c1      20000    2          2         1   24     2      2   
1  8a8c8f3b-8eb4     120000    2          2         2   26    -1      2   
2  85698822-43f5      90000    2          2         2   34     0      0   
3  0737c11b-be42      50000    2          2         1   37     0      0   
4  3b7f77cc-dbc0      50000    1          2         1   57    -1      0   

   PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0     -1     -1  ...          0          0          0         0       689   
1      0      0  ...       3272       3455       3261         0      1000   
2      0      0  ...      14331      14948      15549      1518      1500   
3      0      0  ...      28314      28959      29547      2000      2019   
4     -1      0  ...      20940      19146      19131      2000     36681   

   PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0         0         0         0         0                           1  
1      1000      1000         0      2000                           1  
2      1000      1000      1000      5000                           0  
3      1200      1100      1069      1000                           0  
4     10000      9000       689       679                           0  

[5 rows x 25 columns]

In [41]:
df_clean_2['PAY_1'] = df_clean_2['PAY_1'].astype('int64')
df_clean_2[['PAY_1', 'PAY_2']].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26664 entries, 0 to 29999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   PAY_1   26664 non-null  int64
 1   PAY_2   26664 non-null  int64
dtypes: int64(2)
memory usage: 624.9 KB


In [43]:
df_clean_2['EDUCATION'].replace(to_replace=[0, 5, 6], value=4, inplace=True)
df_clean_2['EDUCATION'].value_counts()

2    12458
1     9412
3     4380
4      414
Name: EDUCATION, dtype: int64

In [44]:
df_clean_2['MARRIAGE'].replace(to_replace=0, value=3, inplace=True)
df_clean_2['MARRIAGE'].value_counts()

2    14158
1    12172
3      334
Name: MARRIAGE, dtype: int64

In [45]:
df_clean_2['EDUCATION_CAT'] = 'none'

In [46]:
df_clean_2[['EDUCATION', 'EDUCATION_CAT']].head(10)

EDUCATION EDUCATION_CAT
0          2          none
1          2          none
2          2          none
3          2          none
4          2          none
5          1          none
6          1          none
7          2          none
8          3          none
9          3          none

In [47]:
cat_mapping = {
    1: "graduate school",
    2: "university",
    3: "high school",
    4: "others"
}

In [48]:
df_clean_2['EDUCATION_CAT'] = df_clean_2['EDUCATION'].map(cat_mapping)
df_clean_2[['EDUCATION', 'EDUCATION_CAT']].head(10)

EDUCATION    EDUCATION_CAT
0          2       university
1          2       university
2          2       university
3          2       university
4          2       university
5          1  graduate school
6          1  graduate school
7          2       university
8          3      high school
9          3      high school

In [49]:
edu_ohe = pd.get_dummies(df_clean_2['EDUCATION_CAT'])
edu_ohe.head(10)

graduate school  high school  others  university
0                0            0       0           1
1                0            0       0           1
2                0            0       0           1
3                0            0       0           1
4                0            0       0           1
5                1            0       0           0
6                1            0       0           0
7                0            0       0           1
8                0            1       0           0
9                0            1       0           0

In [50]:
df_with_ohe = pd.concat([df_clean_2, edu_ohe], axis=1)
df_with_ohe

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_1  PAY_2  \
0      798fc410-45c1      20000    2          2         1   24      2      2   
1      8a8c8f3b-8eb4     120000    2          2         2   26     -1      2   
2      85698822-43f5      90000    2          2         2   34      0      0   
3      0737c11b-be42      50000    2          2         1   37      0      0   
4      3b7f77cc-dbc0      50000    1          2         1   57     -1      0   
...              ...        ...  ...        ...       ...  ...    ...    ...   
29995  ecff42d0-bdc6     220000    1          3         1   39      0      0   
29996  99d1fa0e-222b     150000    1          3         2   43     -1     -1   
29997  95cdd3e7-4f24      30000    1          2         2   37      4      3   
29998  00d03f02-04cd      80000    1          3         1   41      1     -1   
29999  15d69f9f-5ad3      50000    1          2         1   46      0      0   

       PAY_3  PAY_4  ...  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0         -1     -1  ...         0         0         0         0   
1          0      0  ...      1000      1000         0      2000   
2          0      0  ...      1000      1000      1000      5000   
3          0      0  ...      1200      1100      1069      1000   
4         -1      0  ...     10000      9000       689       679   
...      ...    ...  ...       ...       ...       ...       ...   
29995      0      0  ...      5003      3047      5000      1000   
29996     -1     -1  ...      8998       129         0         0   
29997      2     -1  ...     22000      4200      2000      3100   
29998      0      0  ...      1178      1926     52964      1804   
29999      0      0  ...      1430      1000      1000      1000   

       default payment next month  EDUCATION_CAT  graduate school  \
0                               1     university                0   
1                               1     university                0   
2                               0     university                0   
3                               0     university                0   
4                               0     university                0   
...                           ...            ...              ...   
29995                           0    high school                0   
29996                           0    high school                0   
29997                           1     university                0   
29998                           1    high school                0   
29999                           1     university                0   

       high school  others  university  
0                0       0           1  
1                0       0           1  
2                0       0           1  
3                0       0           1  
4                0       0           1  
...            ...     ...         ...  
29995            1       0           0  
29996            1       0           0  
29997            0       0           1  
29998            1       0           0  
29999            0       0           1  

[26664 rows x 30 columns]

In [51]:
df_with_ohe[['EDUCATION_CAT', 'graduate school',
             'high school', 'university', 'others']].head(10)

EDUCATION_CAT  graduate school  high school  university  others
0       university                0            0           1       0
1       university                0            0           1       0
2       university                0            0           1       0
3       university                0            0           1       0
4       university                0            0           1       0
5  graduate school                1            0           0       0
6  graduate school                1            0           0       0
7       university                0            0           1       0
8      high school                0            1           0       0
9      high school                0            1           0       0

In [52]:
df_with_ohe.to_csv('cleaned_data.csv', index=False)